/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as DoctorLoginRouteImport } from './routes/doctor-login'
import { Route as PatientPortalRouteImport } from './routes/patient-portal'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as DoctorRegisterRouteImport } from './routes/doctor/register'
import { Route as PatientDashboardRouteImport } from './routes/patient/dashboard'
import { Route as PatientPrescriptionRouteImport } from './routes/patient/prescription'
import { Route as DoctorConsultationAppointmentIdRouteImport } from './routes/doctor/consultation/$appointmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorLoginRoute = DoctorLoginRouteImport.update({
  id: '/doctor-login',
  path: '/doctor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalRoute = PatientPortalRouteImport.update({
  id: '/patient-portal',
  path: '/patient-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRegisterRoute = DoctorRegisterRouteImport.update({
  id: '/doctor/register',
  path: '/doctor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPrescriptionRoute = PatientPrescriptionRouteImport.update({
  id: '/patient/prescription',
  path: '/patient/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationAppointmentIdRoute =
  DoctorConsultationAppointmentIdRouteImport.update({
    id: '/doctor/consultation/$appointmentId',
    path: '/doctor/consultation/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/doctor-login': typeof DoctorLoginRoute
  '/patient-portal': typeof PatientPortalRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/register': typeof DoctorRegisterRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescription': typeof PatientPrescriptionRoute
  '/doctor/consultation/$appointmentId': typeof DoctorConsultationAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/doctor-login': typeof DoctorLoginRoute
  '/patient-portal': typeof PatientPortalRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/register': typeof DoctorRegisterRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescription': typeof PatientPrescriptionRoute
  '/doctor/consultation/$appointmentId': typeof DoctorConsultationAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/doctor-login': typeof DoctorLoginRoute
  '/patient-portal': typeof PatientPortalRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/register': typeof DoctorRegisterRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescription': typeof PatientPrescriptionRoute
  '/doctor/consultation/$appointmentId': typeof DoctorConsultationAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/doctor-login'
    | '/patient-portal'
    | '/doctor/dashboard'
    | '/doctor/register'
    | '/patient/dashboard'
    | '/patient/prescription'
    | '/doctor/consultation/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment'
    | '/doctor-login'
    | '/patient-portal'
    | '/doctor/dashboard'
    | '/doctor/register'
    | '/patient/dashboard'
    | '/patient/prescription'
    | '/doctor/consultation/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/doctor-login'
    | '/patient-portal'
    | '/doctor/dashboard'
    | '/doctor/register'
    | '/patient/dashboard'
    | '/patient/prescription'
    | '/doctor/consultation/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRoute: typeof AppointmentRoute
  DoctorLoginRoute: typeof DoctorLoginRoute
  PatientPortalRoute: typeof PatientPortalRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorRegisterRoute: typeof DoctorRegisterRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientPrescriptionRoute: typeof PatientPrescriptionRoute
  DoctorConsultationAppointmentIdRoute: typeof DoctorConsultationAppointmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-login': {
      id: '/doctor-login'
      path: '/doctor-login'
      fullPath: '/doctor-login'
      preLoaderRoute: typeof DoctorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal': {
      id: '/patient-portal'
      path: '/patient-portal'
      fullPath: '/patient-portal'
      preLoaderRoute: typeof PatientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/register': {
      id: '/doctor/register'
      path: '/doctor/register'
      fullPath: '/doctor/register'
      preLoaderRoute: typeof DoctorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/prescription': {
      id: '/patient/prescription'
      path: '/patient/prescription'
      fullPath: '/patient/prescription'
      preLoaderRoute: typeof PatientPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultation/$appointmentId': {
      id: '/doctor/consultation/$appointmentId'
      path: '/doctor/consultation/$appointmentId'
      fullPath: '/doctor/consultation/$appointmentId'
      preLoaderRoute: typeof DoctorConsultationAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRoute: AppointmentRoute,
  DoctorLoginRoute: DoctorLoginRoute,
  PatientPortalRoute: PatientPortalRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorRegisterRoute: DoctorRegisterRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientPrescriptionRoute: PatientPrescriptionRoute,
  DoctorConsultationAppointmentIdRoute: DoctorConsultationAppointmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
